# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScannerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScannerDemo
  pod 'WeScan', '~> 1.0.0'
  pod 'PDFGenerator', '~> 3.0.0'

end
